project:
  type: website

website:
  title: "cduarte90.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - proyectos.qmd

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true



