project:
  type: website

website:
  title: "cduarte90.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - proyectos.qmd
  search:
    location: navbar
    type: overlay
  page-navigation: true

  page-footer: 
    center: |
      &copy; 2025 Celeste Duarte


format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true


